# Переопределяем стандартные этапы для выполнения нужных действий
stages:
  - build
  - manual_status

# Определение задачи для сборки Docker-образа
build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
    - docker rmi $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
  rules:
    - if: $CI_COMMIT_TAG
      when: always
      variables:
        DOCKER_IMAGE_TAG: $CI_COMMIT_TAG
    - when: manual
      variables: 
        DOCKER_IMAGE_TAG: $CI_COMMIT_SHORT_SHA


manual_status:
  stage: manual_status
  script:
    - echo "Manual status stage running..."
  when: manual